### ISSUE TITLE
Messages sent from the announcer don't show up in the individual conversations

### ISSUE THREAD

**Issue by thegooman** [Waidhoferj/cpe-messenger#21]
I sent a message to myself via the announcer and it didn't show it the conversations tab

**Comment by Waidhoferj** [comment]
Not expected behavior. Conversations only show up when the user directly texts the messenger.

**Comment by Waidhoferj** [comment]
@kgoo124 It would be cool for active conversations to include announcements within the message flow (like message bubbles in a different color) to provide context to user questions. If this sounds useful, submit an issue as an ``enhancement``.
